/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description 検索の各段階を返す（Claudeを呼ばない = Anthropicキー不要）。
         *
         *     例: GET /search?q=有給は入社何ヶ月で何日？
         *     ベクトル/字面それぞれの順位と、RRF融合後のスコアが見える。
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /**
             * Question
             * @description 質問文
             */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /**
             * Sources
             * @description 根拠に使ったチャンクの出典（重複排除済み）
             */
            sources: string[];
        };
        /**
         * ErrorResponse
         * @description エラー時の共通形。UIはこれをそのまま表示する。
         */
        ErrorResponse: {
            /**
             * Error
             * @description 機械判定用のコード（voyage_rate_limit 等）
             */
            error: string;
            /**
             * Message
             * @description 利用者向けメッセージ
             */
            message: string;
            /**
             * Hint
             * @description 対処のヒント
             * @default
             */
            hint: string;
            /**
             * Detail
             * @description 元の例外メッセージ
             * @default
             */
            detail: string;
        };
        /**
         * FusedHit
         * @description RRFで融合した後の最終順位。
         */
        FusedHit: {
            /** Rank */
            rank: number;
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Score
             * @description RRFスコア。Σ 1/(60 + 各検索での順位)
             */
            score: number;
            /**
             * Vector Rank
             * @description null = ベクトル検索に出てこなかった
             */
            vector_rank: number | null;
            /**
             * Lexical Rank
             * @description null = 字面検索に出てこなかった
             */
            lexical_rank: number | null;
            /** Cosine Similarity */
            cosine_similarity: number | null;
            /** Trgm Similarity */
            trgm_similarity: number | null;
            /** Preview */
            preview: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Source
             * @description 文書名（例: 有給休暇.txt）
             */
            source: string;
            /**
             * Text
             * @description 本文
             */
            text: string;
            /**
             * Category
             * @description 分類（任意）
             */
            category?: string | null;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Source */
            source: string;
            /**
             * Chunks Created
             * @description 作成したチャンク数
             */
            chunks_created: number;
            /**
             * Replaced
             * @description 置き換えた既存文書の件数（0なら新規）
             */
            replaced: number;
        };
        /**
         * LexicalHit
         * @description 字面検索（名詞のトライグラム一致）のヒット。
         */
        LexicalHit: {
            /** Rank */
            rank: number;
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Trgm Similarity
             * @description 0〜1。1に近いほど字面が一致
             */
            trgm_similarity: number;
            /** Preview */
            preview: string;
        };
        /**
         * SearchResponse
         * @description 検索の各段階（Claudeを呼ばない）。
         */
        SearchResponse: {
            /** Question */
            question: string;
            /**
             * Lexical Min Similarity
             * @description これ未満の字面ヒットはRRFに渡さない閾値
             */
            lexical_min_similarity: number;
            /** Vector Search */
            vector_search: components["schemas"]["VectorHit"][];
            /** Lexical Search */
            lexical_search: components["schemas"]["LexicalHit"][];
            /** Fused */
            fused: components["schemas"]["FusedHit"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VectorHit
         * @description ベクトル検索（意味の近さ）のヒット。
         */
        VectorHit: {
            /** Rank */
            rank: number;
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Cosine Similarity
             * @description 1に近いほど意味が近い（1 - コサイン距離）
             */
            cosine_similarity: number;
            /** Cosine Distance */
            cosine_distance: number;
            /** Preview */
            preview: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description APIキー未設定・認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description レート制限 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 外部API呼び出し失敗 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description APIキー未設定・認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description レート制限 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 外部API呼び出し失敗 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description APIキー未設定・認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description レート制限 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 外部API呼び出し失敗 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
