/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description 検索の各段階を返す（Claudeを呼ばない = Anthropicキー不要）。
         *
         *     - GET /search?q=... … 設定の既定の手法で検索
         *     - GET /search?q=...&retrievers=vector,trgm,bm25 … 手法を明示指定して比較
         *
         *     各手法の順位・生スコアと、RRF融合後の寄与内訳(contributions)が返る。
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /**
             * Question
             * @description 質問文
             */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /**
             * Sources
             * @description 根拠に使ったチャンクの出典（重複排除済み）
             */
            sources: string[];
        };
        /**
         * Contribution
         * @description 融合結果1件に対する、各検索手法からの寄与。
         *
         *     RRFは「どの手法が何位に置いたか」の足し合わせなので、
         *     手法ごとの内訳を持たせて寄与を追えるようにする。
         */
        Contribution: {
            /** Retriever */
            retriever: string;
            /**
             * Rank
             * @description null = この手法のリストに出てこなかった
             */
            rank: number | null;
            /**
             * Metric Value
             * @description その手法の生スコア
             */
            metric_value: number | null;
            /**
             * Rrf Term
             * @description この手法が寄与したRRFスコア 1/(k + 順位 + 1)
             */
            rrf_term: number | null;
        };
        /**
         * ErrorResponse
         * @description エラー時の共通形。UIはこれをそのまま表示する。
         */
        ErrorResponse: {
            /**
             * Error
             * @description 機械判定用のコード（voyage_rate_limit 等）
             */
            error: string;
            /**
             * Message
             * @description 利用者向けメッセージ
             */
            message: string;
            /**
             * Hint
             * @description 対処のヒント
             * @default
             */
            hint: string;
            /**
             * Detail
             * @description 元の例外メッセージ
             * @default
             */
            detail: string;
        };
        /**
         * FusedHit
         * @description RRFで融合した後の最終順位。
         */
        FusedHit: {
            /** Rank */
            rank: number;
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Score
             * @description RRFスコア。各手法の rrf_term の合計
             */
            score: number;
            /**
             * Contributions
             * @description 検索手法ごとの内訳。手法を増やすと要素が増える
             */
            contributions: components["schemas"]["Contribution"][];
            /** Preview */
            preview: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /**
             * Source
             * @description 文書名（例: 有給休暇.txt）
             */
            source: string;
            /**
             * Text
             * @description 本文
             */
            text: string;
            /**
             * Category
             * @description 分類（任意）
             */
            category?: string | null;
        };
        /** IngestResponse */
        IngestResponse: {
            /** Source */
            source: string;
            /**
             * Chunks Created
             * @description 作成したチャンク数
             */
            chunks_created: number;
            /**
             * Replaced
             * @description 置き換えた既存文書の件数（0なら新規）
             */
            replaced: number;
        };
        /**
         * RetrieverInfo
         * @description 選択可能な検索手法（UIの切り替え用）。
         */
        RetrieverInfo: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Metric Label */
            metric_label: string;
        };
        /**
         * RetrieverStage
         * @description 検索手法1つ分のランキング（融合前）。
         */
        RetrieverStage: {
            /**
             * Name
             * @description 手法の識別子: vector / trgm / bm25
             */
            name: string;
            /**
             * Label
             * @description 表示名
             */
            label: string;
            /**
             * Metric Label
             * @description metric_value の表示名（cos類似度 等）
             */
            metric_label: string;
            /** Hits */
            hits: components["schemas"]["StageHit"][];
        };
        /**
         * SearchResponse
         * @description 検索の各段階（Claudeを呼ばない）。
         *
         *     検索手法の本数に依らない形にしてあるので、BM25等を足しても構造は変わらない。
         */
        SearchResponse: {
            /** Question */
            question: string;
            /**
             * Retrievers
             * @description この検索で使った手法の並び
             */
            retrievers: string[];
            /**
             * Available Retrievers
             * @description 指定可能な手法の一覧。/search?retrievers=a,b で選べる
             */
            available_retrievers: components["schemas"]["RetrieverInfo"][];
            /**
             * Lexical Min Similarity
             * @description これ未満の字面ヒットはRRFに渡さない閾値（trgm手法用）
             */
            lexical_min_similarity: number;
            /**
             * Stages
             * @description 融合前の各手法のランキング
             */
            stages: components["schemas"]["RetrieverStage"][];
            /** Fused */
            fused: components["schemas"]["FusedHit"][];
        };
        /**
         * StageHit
         * @description ある検索手法1つの中でのヒット。手法によらず同じ形にしてある。
         */
        StageHit: {
            /** Rank */
            rank: number;
            /** Id */
            id: number;
            /** Source */
            source: string;
            /**
             * Metric Value
             * @description その手法が計算した生スコア（cos類似度 / 字面類似度 / BM25スコア）
             */
            metric_value: number;
            /** Preview */
            preview: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ingest_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description APIキー未設定・認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description レート制限 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 外部API呼び出し失敗 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                top_n?: number;
                retrievers?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description APIキー未設定・認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description レート制限 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 外部API呼び出し失敗 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description APIキー未設定・認証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description レート制限 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 外部API呼び出し失敗 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
